(()=>{'use strict';
const $=s=>document.querySelector(s);
let files={target:null,reference:null},documents=null,fullResult=null,result=null,filter='different',version=0;
function notice(text,cls=''){$('#notice').textContent=text;$('#notice').className=cls;}
function invalidate(clearDocs=false){version++;result=null;if(clearDocs){documents=null;fullResult=null;$('#science-range').disabled=true;$('#science-found').textContent='';}$('#stats').hidden=true;$('#filters').hidden=true;$('#result-total').textContent='';$('#results').replaceChildren();}
function validate(f){if(!/\.hwp$/i.test(f.name))throw Error('확장자가 .hwp인 파일을 선택해 주세요.');if(f.size>20*1024*1024)throw Error('파일당 최대 20MB까지 지원합니다.');if(f.size<512)throw Error('파일이 너무 작거나 비어 있습니다.');}
function showNames(){for(const role of ['target','reference']){const f=files[role];$('#'+role+'-name').textContent=f?f.name+' · '+(f.size/1024).toFixed(0)+' KB':role==='target'?'해설·지문 분석 파일':'최신 문제지 파일';$('#slot-'+role).classList.toggle('loaded',!!f);}$('#swap').disabled=!(files.target&&files.reference);$('#apply-scope').disabled=!(files.target&&files.reference);}
async function accept(list,role){try{const arr=Array.from(list);if(!arr.length)return;if(arr.length>2)throw Error('두 파일만 선택해 주세요.');arr.forEach(validate);const next={...files};if(role){if(arr.length!==1)throw Error('이 칸에는 파일 하나를 넣어 주세요.');next[role]=arr[0];}else{const classified=arr.map(file=>({file,role:HwpCompare.classifyName(file.name)}));if(arr.length===2){const roles=classified.map(x=>x.role);if(roles[0]&&roles[0]===roles[1])throw Error('같은 역할의 파일 두 개입니다. 해설지와 문제지를 각각 넣어 주세요.');if(!roles.some(Boolean))throw Error('파일명을 구분하지 못했습니다. 아래 해당 칸에 각각 넣어 주세요.');for(const c of classified)next[c.role||(roles.find(Boolean)==='target'?'reference':'target')]=c.file;}else{const c=classified[0];if(!c.role)throw Error('파일명을 구분하지 못했습니다. 아래 해당 칸에 넣어 주세요.');next[c.role]=c.file;}}
  invalidate(true);files=next;$('#questions').value='';setFilter('different');showNames();if(files.target&&files.reference)await run();else notice('나머지 파일을 넣어 주세요.');
}catch(e){notice(e.message,'error');}}
function dropZone(el,handler){el.addEventListener('dragover',e=>{e.preventDefault();el.classList.add('over');});el.addEventListener('dragleave',()=>el.classList.remove('over'));el.addEventListener('drop',e=>{e.preventDefault();e.stopPropagation();el.classList.remove('over');handler(e.dataTransfer.files);});}
function scoped(full,selection,include){if(selection){const missing=[...selection].filter(q=>!full.available.includes(q));if(missing.length)throw Error('해설지에서 찾지 못한 문제 번호: '+missing.join(', '));}const items=HwpCompare.selectItems(full.items,selection,include).filter(i=>!['definition','analysis-note'].includes(i.kind));return {...full,items,selected:selection?[...selection].sort((a,b)=>a-b):null,counts:Object.fromEntries(['match','different','location','unmatched','review'].map(s=>[s,items.filter(i=>i.status===s).length])),analysisCount:items.filter(i=>i.analysis).length,analysisBlocks:items.filter(i=>i.kind==='analysis-source').length};}
async function run(){const token=version;notice(fullResult?'검사 범위를 적용하고 있습니다…':'전체 문항과 지문 분석을 대조하고 있습니다…','busy');await new Promise(r=>setTimeout(r,25));try{
  if(!documents){const [a,b]=await Promise.all([files.target.arrayBuffer(),files.reference.arrayBuffer()]);if(token!==version)return;documents={target:new HwpTools.Hwp(new Uint8Array(a)),reference:new HwpTools.Hwp(new Uint8Array(b))};}
  if(!fullResult)fullResult=HwpCompare.compare(documents.target,documents.reference);
  if(token!==version)return;const selection=HwpCompare.parseSelection($('#questions').value);result=scoped(fullResult,selection,$('#include-analysis').checked);
  const ranges=fullResult.scienceRanges;$('#science-range').disabled=!ranges.length;$('#science-found').textContent=ranges.length?ranges.map(x=>x.subjects.join('·')+' '+x.range.replace('-','–')+'번').join(' / '):'제목에서 과학·기술 범위를 찾지 못했습니다. 문제 번호를 직접 입력할 수 있습니다.';
  const scope=selection?[...selection].join(', ')+'번':'전체 문항';$('#result-subtitle').textContent=scope+($('#include-analysis').checked?' · 관련 지문 분석 포함':' · 해설만');$('#result-total').textContent=result.items.length+'항목';$('#stats').hidden=false;$('#stats').replaceChildren();
  for(const [label,n] of [['일치',result.counts.match],['문구 차이',result.counts.different],['번호 확인',result.counts.location],['확인 필요',result.items.filter(needsReview).length]]){const d=document.createElement('div');d.className='stat';d.textContent=label;const b=document.createElement('strong');b.textContent=n;d.append(b);$('#stats').append(d);}
  $('#filters').hidden=false;render();notice(scope+' 검사가 끝났습니다. 문구 차이 '+result.counts.different+'개 · 번호 확인 '+result.counts.location+'개 · 확인 필요 '+result.items.filter(needsReview).length+'개');
}catch(e){if(token===version){result=null;notice('처리하지 못했습니다. '+e.message,'error');$('#result-subtitle').textContent='검사 범위 또는 파일을 확인해 주세요.';}}}
function marked(el,text,spans=[]){const bounds=new Set([0,text.length]);for(const s of spans){bounds.add(Math.max(0,Math.min(text.length,s.start)));bounds.add(Math.max(0,Math.min(text.length,s.end)));}const pts=[...bounds].sort((a,b)=>a-b);for(let i=0;i<pts.length-1;i++){const a=pts[i],b=pts[i+1],s=spans.find(s=>a>=s.start&&a<s.end),node=s?document.createElement('mark'):document.createTextNode('');node.textContent=text.slice(a,b);if(s?.anchor){node.className='missing-anchor';node.title='인접 위치에 빠진 내용이 있습니다. 아래 누락 안내를 확인해 주세요.';}el.append(node);}}
function changeLabel(c,it){if(c.type==='replace')return '“'+c.old+'” → “'+c.next+'”';if(c.type==='extra')return '“'+c.old+'” 추가됨';const ch=it.text[c.position]||it.text.trim().slice(-1);return '“'+ch+'” '+(c.anchorDirection==='after'?'뒤':'앞')+'에 “'+c.next+'” 누락';}
function locationLabel(l){if(l.status==='match')return '문장 번호 일치: '+l.expected;return '표기 '+l.expected+' → '+(l.status==='different'?'원문 ':'원문 후보 ')+l.actual;}
function needsReview(it){return ['unmatched','review'].includes(it.status)||it.location?.status==='review';}
function render(){if(!result)return;const rows=result.items.filter(it=>filter==='all'||filter==='different'&&it.status==='different'||filter==='location'&&it.kind==='evidence'||filter==='analysis'&&it.kind==='analysis-source'||filter==='review'&&needsReview(it));$('#results').replaceChildren();if(!rows.length){const d=document.createElement('div');d.className='empty';d.textContent=filter==='analysis'?'현재 범위에서 인식한 지문 분석 원문이 없습니다.':filter==='location'?'현재 범위에서 인식한 문장 번호가 붙은 지문 박스가 없습니다.':'이 분류에 해당하는 항목이 없습니다. 전체 검사 항목에서 일치한 원문도 볼 수 있습니다.';$('#results').append(d);return;}
  const frag=document.createDocumentFragment();for(const it of rows){const article=document.createElement('article');article.className='item';article.dataset.kind=it.kind;const head=document.createElement('div');head.className='item-heading';const pill=document.createElement('span');pill.className='pill '+it.status;pill.textContent={match:'일치',different:'문구 차이',location:'번호 확인',unmatched:'대응 확인 필요',review:'확인 필요'}[it.status];const title=document.createElement('b');title.textContent=it.label;head.append(pill,title);article.append(head);
    if(it.location){const l=document.createElement('p');l.className='location-note '+it.location.status;l.textContent=locationLabel(it.location);article.append(l);}
    const grid=document.createElement('div');grid.className='compare-grid';for(const [label,text,role,spans] of [[it.analysis?'지문 분석지':'해설지',it.text,'target',it.spans],['기준 문제지'+(it.sourceLabel?' · '+it.sourceLabel:''),it.reference||'확정된 대응 원문 없음','reference',it.refSpans]]){const d=document.createElement('div');d.className='text-block '+role;const sm=document.createElement('small');sm.textContent=label;const p=document.createElement('p');marked(p,text,spans);d.append(sm,p);grid.append(d);}article.append(grid);
    if(it.changes.length){const changes=document.createElement('div');changes.className='change-list';for(const c of it.changes){const chip=document.createElement('span');chip.textContent=changeLabel(c,it);changes.append(chip);}article.append(changes);}const note=document.createElement('p');note.className='item-note';note.textContent=it.reason;article.append(note);frag.append(article);
  }$('#results').append(frag);
}
function setFilter(value){filter=value;for(const b of document.querySelectorAll('[data-filter]')){b.classList.toggle('active',b.dataset.filter===value);b.setAttribute('aria-pressed',String(b.dataset.filter===value));}}
function rescope(){if(!files.target||!files.reference)return;invalidate();run();}
$('#pair-drop').addEventListener('click',()=>$('#pair-input').click());$('#pair-drop').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#pair-input').click();}});$('#pair-input').addEventListener('click',e=>e.stopPropagation());$('#pair-input').addEventListener('change',e=>{accept(e.target.files);e.target.value='';});dropZone($('#pair-drop'),f=>accept(f));
for(const role of ['target','reference']){$('#'+role+'-input').addEventListener('change',e=>{accept(e.target.files,role);e.target.value='';});dropZone($('#slot-'+role),f=>accept(f,role));$('#slot-'+role).addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#'+role+'-input').click();}});}
$('#swap').addEventListener('click',()=>{invalidate(true);[files.target,files.reference]=[files.reference,files.target];$('#questions').value='';showNames();run();});$('#apply-scope').addEventListener('click',rescope);$('#questions').addEventListener('keydown',e=>{if(e.key==='Enter')rescope();});$('#include-analysis').addEventListener('change',rescope);
$('#science-range').addEventListener('click',()=>{if(!fullResult?.scienceRanges.length)return;$('#questions').value=fullResult.scienceRanges.map(x=>x.range).join(', ');rescope();});$('#all-range').addEventListener('click',()=>{$('#questions').value='';rescope();});$('#filters').addEventListener('click',e=>{const b=e.target.closest('button[data-filter]');if(!b)return;setFilter(b.dataset.filter);render();});document.addEventListener('dragover',e=>e.preventDefault());document.addEventListener('drop',e=>e.preventDefault());
// Read-only optional browser integration; no document is uploaded by this app.
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_hwp_comparison',description:'현재 화면의 HWP 대조 결과를 조회합니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(input&&Object.keys(input).length)throw Error('입력값이 필요하지 않습니다.');if(!result)throw Error('먼저 두 HWP 파일을 선택해 주세요.');return result;}})).catch(()=>{});}catch{}}
})();
