(function(root){'use strict';
const marker=/[㉠-㉻ⓐ-ⓩ]/;
const normalize=(s,omitMarkers=false)=>s.replace(omitMarkers?/[\s㉠-㉻ⓐ-ⓩ]/g:/\s/g,'');
function normalized(s,omitMarkers=false){let text='',map=[];for(let i=0;i<s.length;i++)if(!/\s/.test(s[i])&&!(omitMarkers&&marker.test(s[i]))){text+=s[i];map.push(i);}return {text,map};}
const rangeRE=/^\[(\d+)\s*[~～∼-]\s*(\d+)\]/;
function sentences(s){let out=[],start=0;for(let i=0;i<s.length;i++)if(/[.!?。]/.test(s[i])&&(i+1===s.length||/\s/.test(s[i+1]))){let a=start,b=i+1;while(a<b&&/\s/.test(s[a]))a++;if(a<b)out.push({text:s.slice(a,b),start:a,end:b});start=b;}let a=start,b=s.length;while(a<b&&/\s/.test(s[a]))a++;while(b>a&&/\s/.test(s[b-1]))b--;if(a<b)out.push({text:s.slice(a,b),start:a,end:b});return out;}
function grams(s){let a=new Set();for(let i=0;i<s.length-1;i++)a.add(s.slice(i,i+2));return a;}
function similarity(a,b){if(a===b)return 1;let aa=grams(a),bb=grams(b),n=0;for(let x of aa)if(bb.has(x))n++;return aa.size+bb.size?2*n/(aa.size+bb.size):0;}
function parseSelection(s){if(!s.trim())return null;let set=new Set();for(let t of s.trim().split(/[,，\s]+/)){let m=t.match(/^(\d+)(?:[-~～](\d+))?$/);if(!m)throw Error('문제 번호는 11, 12 또는 10-13처럼 입력해 주세요.');let a=+m[1],b=m[2]?+m[2]:a;if(a<1||b<a||b>100)throw Error('문제 번호는 1~100 사이의 오름차순 범위로 입력해 주세요.');for(let q=a;q<=b;q++)set.add(q);}return set;}
function classifyName(name){let t=/해설|지문\s*분석|^t1\.hwp$/i.test(name),r=/문제지|^t2\.hwp$/i.test(name);return t!==r?(t?'target':'reference'):null;}
function sourceIndex(doc){let pool=[],paragraphs=[],blocks=[],options=new Map(),range='',q=0,lastOption='',optionKey='',passage=false,pn=0,part='',track='공통';for(let p of doc.paragraphs){let t=p.text.trim();if(!t)continue;let rm=t.match(rangeRE);if(rm){range=rm[1]+'-'+rm[2];q=+rm[1];lastOption='';passage=true;pn=0;part='';continue;}if(/^국어 영역\s*\(화법과 작문\)/.test(t))track='화작';if(/^국어 영역\s*\(언어와 매체\)/.test(t))track='언매';let sub=t.match(/^\(([가나다])\)\s*$/);if(sub&&passage){part=sub[1];pn=0;continue;}let op=t.match(/^([①②③④⑤])\s*(.+)/s);if(op&&op[2].length>5){if(op[1]==='①'&&lastOption==='⑤')q++;lastOption=op[1];passage=false;optionKey=[track,range,q,op[1]].join(':');let item={text:op[2],label:q+'번 '+op[1],range,track,q,kind:'option'};options.set(optionKey,item);pool.push(item);continue;}if(/^ⓑ\s*[:：]/.test(t)&&optionKey){let prev=options.get(optionKey);if(prev)prev.cont=t;continue;}if(/것은[?？]|물음에 답/.test(t)&&!rm){passage=false;continue;}if(t.length<15||/저작권|제\d교시|모의고사.*문제지|국어 영역|^홀수형/.test(t)||!range)continue;
blocks.push({text:t,range,track,q,part,label:'문제지 연속 문장',kind:'block',paraId:p.id});
if(passage){pn++;let para={text:t,range,track,part,pn,label:(part?'('+part+') ':'')+pn+'문단',kind:'passage'};paragraphs.push(para);sentences(t).forEach((s,i)=>pool.push({...para,text:s.text,sn:i+1,label:para.label+' '+(i+1)+'문장'}));}else for(let s of sentences(t))pool.push({text:s.text,range,track,q,label:q+'번 본문·보기',kind:'view'});}
for(let item of options.values())if(item.cont)pool.push({...item,text:item.cont,label:item.label+' ⓑ'});for(let p of pool)p.norm=normalize(p.text);return {pool,paragraphs,blocks,options};}
function targets(doc){let items=[],range='',q=0,choice='',analysis=false,pn=0,part='',afterLabel=false,track='공통';const add=(p,start,end,kind,label,extra={})=>{while(start<end&&/\s/.test(p.text[start]))start++;while(end>start&&/\s/.test(p.text[end-1]))end--;if(start===end)return;items.push({id:items.length,paraId:p.id,start,end,text:p.text.slice(start,end),kind,label,range,q:analysis?null:q,choice,pn,part,track,analysis,...extra});};for(let p of doc.paragraphs){let t=p.text,tr=t.trim();if(!tr)continue;if(/주요\s*지문\s*분석|^지문\s*분석(?:지)?$/.test(tr)){analysis=true;q=0;pn=0;part='';continue;}if(/선택 과목.*화법과 작문.*해설/.test(tr))track='화작';if(/선택 과목.*언어와 매체.*해설/.test(tr))track='언매';let rm=tr.match(rangeRE);if(rm){range=rm[1]+'-'+rm[2];part='';pn=0;afterLabel=false;if(+rm[1]<35)track='공통';continue;}if(analysis){let sub=tr.match(/^\(([가나다])\)$/);if(sub){part=sub[1];pn=0;continue;}let pm=tr.match(/^(\d+)\s*문단$/);if(pm){pn=+pm[1];afterLabel=true;continue;}if(!pn)continue;if(afterLabel||(/다\.[\s]*$/.test(t)&&!/^\s*[•▶→↳]/.test(t)&&normalize(t).length>30)){for(let s of sentences(t))add(p,s.start,s.end,'analysis-source',range+' 지문 분석 '+(part?'('+part+') ':'')+pn+'문단',{firstCopy:afterLabel});afterLabel=false;}else if(tr.length>=8)add(p,0,t.length,'analysis-note',range+' 지문 분석 '+pn+'문단 설명');continue;}
let qm=tr.match(/^(\d+)\.\s*.+정답/);if(qm){q=+qm[1];choice='';part='';continue;}if(!q)continue;let numbered=[...t.matchAll(/(?:\(([가나다])\)\s*[-－]?\s*)?([➊➋➌➍➎➏➐➑➒➓❶❷❸❹❺❻❼❽❾❿]|(?<=^\s*)\d{1,2})\s*[-－]\s*(\d+)\s*/g)];if(numbered.length){for(let i=0;i<numbered.length;i++){let m=numbered[i],start=m.index+m[0].length,end=i+1<numbered.length?numbered[i+1].index:t.length;if(m[1])part=m[1];let np='➊➋➌➍➎➏➐➑➒➓'.indexOf(m[2])+1;if(!np)np='❶❷❸❹❺❻❼❽❾❿'.indexOf(m[2])+1;if(!np)np=+m[2];let chunk=t.slice(start,end),re=/\(\s*[…⋯]+\s*\)|[…⋯]+|\.{3,}/g,pos=0,em;let extra={pn:np,sn:+m[3],part};while((em=re.exec(chunk))){if(em.index>pos)add(p,start+pos,start+em.index,'evidence',q+'번 근거 '+m[0].trim(),extra);pos=em.index+em[0].length;}if(pos<chunk.length)add(p,start+pos,end,'evidence',q+'번 근거 '+m[0].trim(),extra);}continue;}
let op=t.match(/^\s*([①②③④⑤])\s*/);if(op&&tr.length>8){choice=op[1];add(p,op[0].length,t.length,'option',q+'번 '+choice+' 선지');continue;}if(/^\s*ⓑ\s*[:：]/.test(t)&&choice){add(p,0,t.length,'option-cont',q+'번 '+choice+' 선지 ⓑ');continue;}
if(/^\s*<보기>/.test(t)){let start=t.indexOf('<보기>')+4,chunk=t.slice(start),re=/\(\s*[…⋯]+\s*\)|[…⋯]+|\.{3,}/g,pos=0,m;while((m=re.exec(chunk))){if(m.index>pos)add(p,start+pos,start+m.index,'view',q+'번 <보기> 발췌');pos=m.index+m[0].length;}if(pos<chunk.length)add(p,start+pos,t.length,'view',q+'번 <보기> 발췌');continue;}
if(/^\s*▶/.test(t)){let re=/‘([^’]*)’|“([^”]*)”|「([^」]*)」|『([^』]*)』/g,m;while((m=re.exec(t))){let inner=m[1]??m[2]??m[3]??m[4];if(!normalize(inner))continue;add(p,m.index+1,m.index+1+inner.length,'quote',q+'번 '+choice+' 해설 인용');}}}return items;}
// Alignment keeps an offset map into the untouched HWP text. Analysis copies
// and narrative quotes omit markers; numbered evidence retains them.
function align(target,source,partial=false,analysis=false){const a=normalized(target),b=normalized(source,analysis),n=a.text.length,m=b.text.length;if(!n||!m||n*m>3000000)return null;let cols=m+1,dp=new Uint16Array((n+1)*cols);for(let j=0;j<=m;j++)dp[j]=partial?0:j;for(let i=1;i<=n;i++){dp[i*cols]=i;for(let j=1;j<=m;j++)dp[i*cols+j]=Math.min(dp[(i-1)*cols+j]+1,dp[i*cols+j-1]+1,dp[(i-1)*cols+j-1]+(a.text[i-1]===b.text[j-1]?0:1));}let end=m;if(partial)for(let j=0;j<=m;j++)if(dp[n*cols+j]<dp[n*cols+end])end=j;let i=n,j=end,ops=[];while(i>0||(!partial&&j>0)){let v=dp[i*cols+j];if(i>0&&j>0&&a.text[i-1]===b.text[j-1]&&v===dp[(i-1)*cols+j-1]){ops.push({type:'equal',ai:i-1,bj:j-1});i--;j--;}else if(i>0&&j>0&&v===dp[(i-1)*cols+j-1]+1){ops.push({type:'replace',ai:i-1,bj:j-1});i--;j--;}else if(j>0&&v===dp[i*cols+j-1]+1){ops.push({type:'missing',ai:i,bj:j-1});j--;}else if(i>0){ops.push({type:'extra',ai:i-1,bj:j});i--;}else break;}let start=j;ops.reverse();if(partial&&start>0&&marker.test(b.text[start-1])){ops.unshift({type:'missing',ai:0,bj:start-1});start--;}
let changes=[],group=null;for(let op of ops){if(op.type==='equal'){group=null;continue;}if(!group){group={aStart:op.ai,aEnd:op.ai,bStart:op.bj,bEnd:op.bj};changes.push(group);}if(op.type!=='missing')group.aEnd=op.ai+1;if(op.type!=='extra')group.bEnd=op.bj+1;}
let spans=[],refSpans=[],details=[];for(let c of changes){let ast=c.aStart<n?a.map[c.aStart]:target.length,aend=c.aEnd>c.aStart?a.map[c.aEnd-1]+1:ast,bst=c.bStart<m?b.map[c.bStart]:source.length,bend=c.bEnd>c.bStart?b.map[c.bEnd-1]+1:bst;let old=target.slice(ast,aend),next=source.slice(bst,bend);if(old)spans.push({start:ast,end:aend,anchor:false});else{let anchor=c.aStart<n?a.map[c.aStart]:a.map[n-1];spans.push({start:anchor,end:anchor+1,anchor:true});}if(next)refSpans.push({start:bst,end:bend});details.push({type:old?(next?'replace':'extra'):'missing',old,next,position:ast,anchorDirection:ast>=target.length?'after':'before'});}
return {spans,refSpans,changes:details,cost:dp[n*cols+end],coverage:n?1-dp[n*cols+end]/Math.max(n,end-start):0};}
function selectItems(items,selection,includeAnalysis=true){return items.filter(it=>{if(it.analysis&&!includeAnalysis)return false;if(!selection)return true;if(!it.analysis)return selection.has(it.q);let [a,b]=it.range.split('-').map(Number);return [...selection].some(q=>q>=a&&q<=b);});}
function quoteWindows(blocks,text,omitMarkers){let count=sentences(text).length,out=[];for(let b of blocks){let ss=sentences(b.text);for(let i=0;i<ss.length;i++)for(let size=Math.max(1,count-1);size<=count+1&&i+size<=ss.length;size++){let t=b.text.slice(ss[i].start,ss[i+size-1].end);out.push({...b,text:t,norm:normalize(t,omitMarkers)});}}return out;}
function compare(target,reference,opts={}){let src=sourceIndex(reference),all=targets(target),selection=typeof opts.questions==='string'?parseSelection(opts.questions):opts.questions||null,chosen=selectItems(all,selection,opts.includeAnalysis!==false),available=[...new Set(all.filter(i=>!i.analysis).map(i=>i.q))].sort((a,b)=>a-b);if(selection){let invalid=[...selection].filter(q=>!available.includes(q));if(invalid.length)throw Error('해설지에서 찾지 못한 문제 번호: '+invalid.join(', '));}if(!chosen.length)throw Error('선택한 범위에서 검사할 항목을 찾지 못했습니다.');const unknown=(it,ref,reason,status='unmatched')=>({...it,status,reference:ref?.text||'',sourceLabel:ref?.label||'',reason,spans:[],refSpans:[],changes:[]});
let results=chosen.map(it=>{let omitMarkers=it.analysis||it.kind==='quote',n=normalize(it.text),scope=src.pool.filter(s=>s.range===it.range&&s.track===it.track);if(!scope.length)scope=src.pool.filter(s=>s.range===it.range);scope=scope.map(s=>({...s,norm:normalize(s.text,omitMarkers)}));let body=scope.filter(s=>s.kind==='passage');let direct=null,partial=false,reason='';
if(it.kind==='analysis-note'){let para=src.paragraphs.find(s=>s.range===it.range&&s.pn===it.pn&&s.part===it.part);return unknown(it,para,'요약·설명은 원문과 함께 확인해 주세요. 문구 차이로 자동 강조하지 않습니다.','review');}
if(it.kind==='option'||it.kind==='option-cont'){direct=src.options.get([it.track,it.range,it.q,it.choice].join(':'));if(!direct)return unknown(it,null,'같은 문항·선지의 원문을 찾지 못했습니다.');direct={...direct,text:it.kind==='option-cont'?direct.cont||'':direct.text};reason='같은 문항·선지 대조';}
else if(it.kind==='evidence'){let labelled=body.filter(s=>s.pn===it.pn&&s.sn===it.sn&&(!it.part||s.part===it.part));if(labelled.length===1&&similarity(n,labelled[0].norm)>.4){direct=labelled[0];reason='문단·문장 번호로 연결 · 참조 기호 포함';}}
else if(it.kind==='analysis-source'){let paraBody=body.filter(s=>s.pn===it.pn&&s.part===it.part),candidates=paraBody.map(s=>({...s,score:similarity(n,normalize(s.text,true))})).sort((a,b)=>b.score-a.score);if(candidates[0]?.score>=.5&&(candidates.length===1||candidates[0].score-candidates[1].score>.08)){direct=candidates[0];reason='지문 분석 원문 대조 · 기준 지문의 참조 기호 제외';}else return unknown(it,src.paragraphs.find(s=>s.range===it.range&&s.pn===it.pn&&s.part===it.part),'원문 복사 구간인지 연결을 확인해 주세요.','review');}
if(!direct){let blocks=src.blocks.filter(s=>s.range===it.range&&s.track===it.track).map(s=>({...s,norm:normalize(s.text,omitMarkers)}));let search=it.kind==='quote'?[...scope,...blocks]:scope;let exact=search.filter(s=>s.norm.includes(n));if(exact.length){direct=exact[0];partial=true;reason=exact.length>1?'같은 문구가 여러 위치에 있습니다.':'원문 일부와 대조';}else if(it.kind==='view'){let candidates=scope.filter(s=>s.kind==='view'),joined=candidates.map(s=>s.text).join(' ');if(joined){direct={text:joined,label:'문제지 <보기>'};partial=true;reason='보기 발췌와 대조';}}
if(!direct){let candidates=it.kind==='quote'?quoteWindows(blocks,it.text,omitMarkers):(body.length?body:scope);let scored=candidates.map(s=>({...s,score:similarity(n,s.norm)})).sort((a,b)=>b.score-a.score),best=scored[0],second=scored[1];if(best&&best.score>=.55&&(!second||best.score-second.score>=.08||best.norm===second.norm)){direct=best;partial=it.kind==='quote';reason='유사 원문 연결 · 위치 확인 필요';}else return unknown(it,best?.score>.2?best:null,'대응을 확정하지 못해 HWP에 색을 입히지 않았습니다.');}}
let diff=align(it.text,direct.text,partial,omitMarkers);if(!diff)return unknown(it,direct,'안전하게 글자 차이를 계산할 수 없어 자동 강조하지 않았습니다.');if(diff.coverage<.45)return unknown(it,direct,'대응 문구의 차이가 커서 자동 강조하지 않았습니다.');return {...it,status:diff.changes.length?'different':'match',reference:direct.text,sourceLabel:direct.label,reason,...diff};});return {items:results,available,selected:selection?[...selection].sort((a,b)=>a-b):null,counts:{match:results.filter(x=>x.status==='match').length,different:results.filter(x=>x.status==='different').length,unmatched:results.filter(x=>x.status==='unmatched').length,review:results.filter(x=>x.status==='review').length},analysisCount:results.filter(x=>x.analysis).length};}
root.HwpCompare={compare,normalize,normalized,targets,sourceIndex,align,parseSelection,classifyName,selectItems};
})(globalThis);
