(function(root){'use strict';
const marker=/[㉠-㉻ⓐ-ⓩ]/;
const normalize=(s,omitMarkers=false)=>s.replace(omitMarkers?/[\s㉠-㉻ⓐ-ⓩ]/g:/\s/g,'');
function normalized(s,omitMarkers=false){let text='',map=[];for(let i=0;i<s.length;i++)if(!/\s/.test(s[i])&&!(omitMarkers&&marker.test(s[i]))){text+=s[i];map.push(i);}return {text,map};}
function parseSelection(s){if(!s.trim())return null;let set=new Set();for(let t of s.trim().split(/[,，\s]+/)){let m=t.match(/^(\d+)(?:[-~～](\d+))?$/);if(!m)throw Error('문제 번호는 11, 12 또는 10-13처럼 입력해 주세요.');let a=+m[1],b=m[2]?+m[2]:a;if(a<1||b<a||b>100)throw Error('문제 번호는 1~100 사이의 오름차순 범위로 입력해 주세요.');for(let q=a;q<=b;q++)set.add(q);}return set;}
function classifyName(name){let t=/해설|지문\s*분석|^t1\.hwp$/i.test(name),r=/문제지|^t2\.hwp$/i.test(name);return t!==r?(t?'target':'reference'):null;}
// Alignment keeps an offset map into the untouched HWP text. Analysis copies
// and narrative quotes omit markers; numbered evidence retains them.
function align(target,source,partial=false,analysis=false){const a=normalized(target),b=normalized(source,analysis),n=a.text.length,m=b.text.length;if(!n||!m||n*m>3000000)return null;let cols=m+1,dp=new Uint16Array((n+1)*cols);for(let j=0;j<=m;j++)dp[j]=partial?0:j;for(let i=1;i<=n;i++){dp[i*cols]=i;for(let j=1;j<=m;j++)dp[i*cols+j]=Math.min(dp[(i-1)*cols+j]+1,dp[i*cols+j-1]+1,dp[(i-1)*cols+j-1]+(a.text[i-1]===b.text[j-1]?0:1));}let end=m;if(partial)for(let j=0;j<=m;j++)if(dp[n*cols+j]<dp[n*cols+end])end=j;let i=n,j=end,ops=[];while(i>0||(!partial&&j>0)){let v=dp[i*cols+j];if(i>0&&j>0&&a.text[i-1]===b.text[j-1]&&v===dp[(i-1)*cols+j-1]){ops.push({type:'equal',ai:i-1,bj:j-1});i--;j--;}else if(i>0&&j>0&&v===dp[(i-1)*cols+j-1]+1){ops.push({type:'replace',ai:i-1,bj:j-1});i--;j--;}else if(j>0&&v===dp[i*cols+j-1]+1){ops.push({type:'missing',ai:i,bj:j-1});j--;}else if(i>0){ops.push({type:'extra',ai:i-1,bj:j});i--;}else break;}let start=j;ops.reverse();if(partial&&start>0&&marker.test(b.text[start-1])){ops.unshift({type:'missing',ai:0,bj:start-1});start--;}
let changes=[],group=null;for(let op of ops){if(op.type==='equal'){group=null;continue;}if(!group){group={aStart:op.ai,aEnd:op.ai,bStart:op.bj,bEnd:op.bj};changes.push(group);}if(op.type!=='missing')group.aEnd=op.ai+1;if(op.type!=='extra')group.bEnd=op.bj+1;}
let spans=[],refSpans=[],details=[];for(let c of changes){let ast=c.aStart<n?a.map[c.aStart]:target.length,aend=c.aEnd>c.aStart?a.map[c.aEnd-1]+1:ast,bst=c.bStart<m?b.map[c.bStart]:source.length,bend=c.bEnd>c.bStart?b.map[c.bEnd-1]+1:bst;let old=target.slice(ast,aend),next=source.slice(bst,bend);if(old)spans.push({start:ast,end:aend,anchor:false});else{let anchor=c.aStart<n?a.map[c.aStart]:a.map[n-1];spans.push({start:anchor,end:anchor+1,anchor:true});}if(next)refSpans.push({start:bst,end:bend});details.push({type:old?(next?'replace':'extra'):'missing',old,next,position:ast,anchorDirection:ast>=target.length?'after':'before'});}
return {sourceStart:b.map[start]??source.length,sourceEnd:end?b.map[end-1]+1:0,spans,refSpans,changes:details,cost:dp[n*cols+end],coverage:n?1-dp[n*cols+end]/Math.max(n,end-start):0};}
function selectItems(items,selection,includeAnalysis=true){return items.filter(it=>{if(it.analysis&&!includeAnalysis)return false;if(!selection)return true;if(!it.analysis)return selection.has(it.q);let [a,b]=it.range.split('-').map(Number);return [...selection].some(q=>q>=a&&q<=b);});}
root.HwpCompare={normalize,normalized,align,parseSelection,classifyName,selectItems};
})(globalThis);
