/* HWP 5.x raw-record editor. Format: Hancom public specification rev 1.3.
 * Reference review: github.com/edwardkim/rhwp serializer/char_shape.rs.
 * Untouched streams and records are copied verbatim; no layout reconstruction. */
(function(root){'use strict';
const END=0xfffffffe,FREE=0xffffffff,FAT=0xfffffffd,DIF=0xfffffffc;
const view=b=>new DataView(b.buffer,b.byteOffset,b.byteLength),u32=(b,o)=>view(b).getUint32(o,true),u16=(b,o)=>view(b).getUint16(o,true),put32=(b,o,n)=>view(b).setUint32(o,n,true),put16=(b,o,n)=>view(b).setUint16(o,n,true);
function concat(arr){let n=arr.reduce((n,b)=>n+b.length,0);if(n>180*1024*1024)throw Error('문서가 너무 큽니다.');let out=new Uint8Array(n),p=0;for(const b of arr){out.set(b,p);p+=b.length;}return out;}
function words(a,size){let b=new Uint8Array(size||a.length*4);for(let i=0;i<a.length;i++)put32(b,i*4,a[i]);return b;}
class Compound{
 constructor(bytes){this.bytes=bytes;const magic=[208,207,17,224,161,177,26,225];if(!magic.every((v,i)=>bytes[i]===v))throw Error('HWP 5.x 파일이 아닙니다. HWPX·PDF는 지원하지 않습니다.');this.sz=2**u16(bytes,30);if(![512,4096].includes(this.sz)||u16(bytes,32)!==6)throw Error('지원하지 않는 HWP 저장 구조입니다.');let dif=[];for(let i=0;i<109;i++)dif.push(u32(bytes,76+i*4));let s=u32(bytes,68),dn=u32(bytes,72);if(dn>1000)throw Error('잘못된 문서 구조입니다.');for(let i=0;i<dn;i++){let d=this.sector(s);for(let j=0;j<this.sz/4-1;j++)dif.push(u32(d,j*4));s=u32(d,this.sz-4);}this.fat=[];const nf=u32(bytes,44);for(const n of dif.filter(x=>x<DIF).slice(0,nf)){let d=this.sector(n);for(let j=0;j<this.sz;j+=4)this.fat.push(u32(d,j));}this.dir=this.chain(u32(bytes,48),this.fat,n=>this.sector(n));this.entries=[];const dec=new TextDecoder('utf-16le');for(let p=0;p+128<=this.dir.length;p+=128){const raw=this.dir.slice(p,p+128),nl=u16(raw,64);if(nl>64)throw Error('잘못된 디렉터리입니다.');this.entries.push({raw,name:dec.decode(raw.slice(0,Math.max(0,nl-2))),type:raw[66],start:u32(raw,116),size:u32(raw,120)});}const rt=this.entries[0];this.mini=this.chain(rt.start,this.fat,n=>this.sector(n)).slice(0,rt.size);let mf=this.chain(u32(bytes,60),this.fat,n=>this.sector(n));this.mfat=[];for(let i=0;i<mf.length;i+=4)this.mfat.push(u32(mf,i));for(const e of this.entries)if(e.type===2){e.data=(e.size<4096?this.chain(e.start,this.mfat,n=>this.mini.slice(n*64,n*64+64)):this.chain(e.start,this.fat,n=>this.sector(n))).slice(0,e.size);if(e.data.length!==e.size)throw Error('문서 스트림을 완전히 읽지 못했습니다.');}this.paths=new Map();const seen=new Set();const walk=(id,path)=>{if(id===FREE)return;if(id>=this.entries.length||seen.has(id))throw Error('문서 디렉터리가 손상되었습니다.');seen.add(id);const e=this.entries[id];walk(u32(e.raw,68),path);e.path=path+e.name;this.paths.set(e.path,e);if(e.type===1)walk(u32(e.raw,76),e.path+'/');walk(u32(e.raw,72),path);};walk(u32(rt.raw,76),'');}
 sector(n){if(n>=Math.floor(this.bytes.length/this.sz)-1)throw Error('문서 섹터 범위를 벗어났습니다.');return this.bytes.slice((n+1)*this.sz,(n+2)*this.sz);}
 chain(s,fat,get){let a=[],seen=new Set();while(s<DIF){if(s>=fat.length||seen.has(s)||seen.size>400000)throw Error('문서 연결 구조가 손상되었습니다.');seen.add(s);a.push(get(s));s=fat[s];}return concat(a);}
 get(path){let e=this.paths.get(path);if(!e)throw Error('필수 문서 정보가 없습니다: '+path);return e.data;}
 write(replacements){let entries=this.entries.map(e=>({...e,raw:e.raw.slice(),data:replacements.get(e.path)||e.data}));const sz=this.sz,sectors=[],fat=[];function alloc(data){if(!data.length)return END;let start=sectors.length,n=Math.ceil(data.length/sz);for(let i=0;i<n;i++){let b=new Uint8Array(sz);b.set(data.subarray(i*sz,(i+1)*sz));sectors.push(b);fat.push(i===n-1?END:start+i+1);}return start;}
 let mini=[],mf=[];for(let e of entries){if(e.type!==2)continue;let d=e.data,start;if(d.length&&d.length<4096){start=mini.length;let n=Math.ceil(d.length/64);for(let i=0;i<n;i++){let b=new Uint8Array(64);b.set(d.subarray(i*64,(i+1)*64));mini.push(b);mf.push(i===n-1?END:start+i+1);}}else start=alloc(d);put32(e.raw,116,start);put32(e.raw,120,d.length);put32(e.raw,124,0);}
 let miniData=concat(mini),miniStart=alloc(miniData);put32(entries[0].raw,116,miniStart);put32(entries[0].raw,120,miniData.length);put32(entries[0].raw,124,0);let mfCount=Math.ceil(mf.length*4/sz),mfBytes=new Uint8Array(mfCount*sz);mfBytes.fill(255);for(let i=0;i<mf.length;i++)put32(mfBytes,i*4,mf[i]);let mfStart=alloc(mfBytes),dirStart=alloc(concat(entries.map(e=>e.raw))),base=sectors.length,nfat=0,ndif=0;while(true){let nf=Math.ceil((base+nfat+ndif)/(sz/4)),nd=nf>109?Math.ceil((nf-109)/(sz/4-1)):0;if(nf===nfat&&nd===ndif)break;nfat=nf;ndif=nd;}let fatIds=Array.from({length:nfat},(_,i)=>base+i),difIds=Array.from({length:ndif},(_,i)=>base+nfat+i);fat.push(...fatIds.map(()=>FAT),...difIds.map(()=>DIF));for(let i=0;i<nfat;i++){let b=new Uint8Array(sz);b.fill(255);for(let j=0;j<sz/4;j++){let k=i*sz/4+j;if(k<fat.length)put32(b,j*4,fat[k]);}sectors.push(b);}for(let i=0;i<ndif;i++){let b=new Uint8Array(sz);b.fill(255);for(let j=0;j<sz/4-1;j++){let k=109+i*(sz/4-1)+j;if(k<nfat)put32(b,j*4,fatIds[k]);}put32(b,sz-4,i===ndif-1?END:difIds[i+1]);sectors.push(b);}let h=this.bytes.slice(0,sz);put32(h,40,sz===4096?Math.ceil(entries.length*128/sz):0);put32(h,44,nfat);put32(h,48,dirStart);put32(h,52,0);put32(h,60,mfStart);put32(h,64,mfCount);put32(h,68,ndif?difIds[0]:END);put32(h,72,ndif);h.fill(255,76,512);for(let i=0;i<Math.min(109,nfat);i++)put32(h,76+i*4,fatIds[i]);return concat([h,...sectors]);}
}
function records(b){let rs=[],p=0;while(p<b.length){if(p+4>b.length)throw Error('잘린 HWP 레코드입니다.');let h=u32(b,p);p+=4;let size=h>>>20;if(size===4095){if(p+4>b.length)throw Error('잘린 HWP 레코드입니다.');size=u32(b,p);p+=4;}if(p+size>b.length)throw Error('HWP 레코드 길이가 맞지 않습니다.');rs.push({tag:h&1023,level:(h>>>10)&1023,data:b.slice(p,p+size)});p+=size;if(rs.length>500000)throw Error('문서가 너무 복잡합니다.');}return rs;}
function serialize(rs){return concat(rs.map(r=>{let n=r.data.length,h=new Uint8Array(n>=4095?8:4);put32(h,0,(r.tag|(r.level<<10)|(Math.min(n,4095)<<20))>>>0);if(n>=4095)put32(h,4,n);return concat([h,r.data]);}));}
const ext=new Set([1,2,3,4,5,6,7,8,9,11,12,14,15,16,17,18,19,20,21,22,23]);
function textRecord(b){let text='',map=[];for(let p=0;p+1<b.length;){let c=u16(b,p);if(ext.has(c)){if(c===9){text+='\t';map.push(p/2);}p+=16;continue;}if(c>=32||c===10||c===13){text+=c===13?'\n':String.fromCharCode(c);map.push(p/2);}p+=2;}return {text,map};}
function inflate(b){const infl=new root.pako.Inflate({raw:true});let chunks=[],len=0;infl.onData=c=>{len+=c.length;if(len>80*1024*1024)throw Error('압축 해제된 문서가 너무 큽니다.');chunks.push(c);};infl.push(b,true);if(infl.err)throw Error('문서 압축을 해제하지 못했습니다.');return concat(chunks);}
class Hwp{
 constructor(bytes){this.cfb=new Compound(bytes);const head=this.cfb.get('FileHeader');if(new TextDecoder().decode(head.slice(0,17))!=='HWP Document File')throw Error('한글 문서가 아닙니다.');this.flags=u32(head,36);if(this.flags&(2|4|16|256|512|1024))throw Error('암호·배포용·서명·보호 문서는 지원하지 않습니다. 보호를 해제한 사본을 사용해 주세요.');this.compressed=!!(this.flags&1);const unpack=b=>this.compressed?inflate(b):b;this.info=records(unpack(this.cfb.get('DocInfo')));this.sections=[];this.paragraphs=[];let entries=[...this.cfb.paths.values()].filter(e=>/^BodyText\/Section\d+$/.test(e.path)).sort((a,b)=>Number(a.name.slice(7))-Number(b.name.slice(7)));if(!entries.length)throw Error('본문을 찾을 수 없습니다.');for(let entry of entries){let section={path:entry.path,records:records(unpack(entry.data))};this.sections.push(section);let stack=[];for(let i=0;i<section.records.length;i++){let r=section.records[i];if(r.tag===66){while(stack.length&&stack.at(-1).header.level>=r.level)stack.pop();let p={id:this.paragraphs.length,section,header:r,headerIndex:i,shape:null,text:'',map:[],textRec:null};this.paragraphs.push(p);stack.push(p);}else if(r.tag===67||r.tag===68){let p=[...stack].reverse().find(p=>p.header.level+1===r.level);if(!p)throw Error('본문 문단 구조를 해석하지 못했습니다.');if(r.tag===67){if(p.textRec)throw Error('복합 텍스트 문단은 아직 지원하지 않습니다.');p.textRec=r;Object.assign(p,textRecord(r.data));}else p.shape=r;}}}if(this.paragraphs.length>12000)throw Error('프로토타입에서는 12,000개 이하의 문단만 지원합니다.');}
 highlight(items){const shapes=this.info.filter(r=>r.tag===21),maprec=this.info.find(r=>r.tag===17);if(!shapes.length||!maprec||maprec.data.length<40)throw Error('글자 서식 정보를 찾지 못했습니다.');let cloned=new Map(),added=[];const green=id=>{if(cloned.has(id))return cloned.get(id);let orig=shapes[id];if(!orig||orig.data.length<56)throw Error('지원하지 않는 글자 서식입니다.');let d=orig.data.slice();put32(d,46,u32(d,46)|3);put32(d,52,0x00408000);let nid=shapes.length+added.length;added.push({tag:21,level:orig.level,data:d});cloned.set(id,nid);return nid;};let ranges=new Map();for(const it of items){if(it.status!=='different'||!it.spans?.length)continue;let p=this.paragraphs[it.paraId];if(!p?.textRec||!p.shape)throw Error('표시할 문단의 글자 서식을 찾지 못했습니다.');for(const span of it.spans){const a=it.start+span.start,b=it.start+span.end,start=p.map[a],end=b<p.map.length?p.map[b]:p.textRec.data.length/2;if(start===undefined||end<=start||a<it.start||b>it.end)throw Error('표시 구간이 잘못되었습니다.');if(!ranges.has(p.id))ranges.set(p.id,[]);ranges.get(p.id).push([start,end]);}}
 let modified=new Map();for(const [id,rs] of ranges){let p=this.paragraphs[id],d=p.shape.data;if(d.length%8)throw Error('문단 글자 서식이 손상되었습니다.');let runs=[];for(let i=0;i<d.length;i+=8)runs.push([u32(d,i),u32(d,i+4)]);if(!runs.length||runs[0][0]!==0)throw Error('문단 시작 서식이 없습니다.');let points=[...new Set([...runs.map(r=>r[0]),...rs.flat()])].sort((a,b)=>a-b),newRuns=[],ridx=0;for(const pos of points){if(pos>=p.textRec.data.length/2)continue;while(ridx+1<runs.length&&runs[ridx+1][0]<=pos)ridx++;let style=runs[ridx][1];if(rs.some(([a,b])=>pos>=a&&pos<b))style=green(style);if(!newRuns.length||newRuns.at(-1)[1]!==style)newRuns.push([pos,style]);}if(newRuns.length>65535)throw Error('글자 서식 구간이 너무 많습니다.');modified.set(p.shape,{...p.shape,data:words(newRuns.flat())});let hd=p.header.data.slice();put16(hd,12,newRuns.length);modified.set(p.header,{...p.header,data:hd});}
 let newInfo=[],inserted=false;for(let i=0;i<this.info.length;i++){let r=this.info[i];if(r===maprec){let d=r.data.slice();put32(d,36,shapes.length+added.length);newInfo.push({...r,data:d});}else newInfo.push(r);if(r.tag===21&&this.info[i+1]?.tag!==21&&!inserted){newInfo.push(...added);inserted=true;}}const pack=rs=>{let b=serialize(rs);return this.compressed?root.pako.deflateRaw(b):b;};let replacements=new Map([['DocInfo',pack(newInfo)]]);for(let s of this.sections)if(s.records.some(r=>modified.has(r)))replacements.set(s.path,pack(s.records.map(r=>modified.get(r)||r)));let output=this.cfb.write(replacements);const verified=new Hwp(output);if(verified.paragraphs.length!==this.paragraphs.length||verified.paragraphs.some((p,i)=>p.text!==this.paragraphs[i].text))throw Error('저장 검증에 실패했습니다. 결과 파일을 제공하지 않습니다.');return output;}
}
root.HwpTools={Hwp,Compound,records,serialize,u32,u16};
})(globalThis);
